---
- name: Install needed packages
  when: ansible_distribution
  ansible.builtin.package:
    name: "{{ nginx_packages }}"

- name: Install pip packages
  ansible.builtin.pip:
    name: "{{ nginx_pip_packages }}"

- name: Include Tasks for nginx
  ansible.builtin.include_tasks: nginx.yml
