- name: Create logs directories
  ansible.builtin.file:
    path: "{{ item.path }}"
    state: "{{ item.state }}"
    recurse: "{{ item.recurse | default(omit) }}"
    owner: "{{ item.owner | default('root') }}"
    group: "{{ item.group | default('root') }}"
    mode: "{{ item.mode | default('0755') }}"

- name: Create files for nginx
  ansible.builtin.copy:
    dest: "{{ item.dest }}"
    content: "{{ item.content }}"
    owner: nginx
    group: nginx
    mode: "0644"
  notify:
    - restart_nginx
