---
- name: Create logs directories and files
  ansible.builtin.file:
    path: "{{ item.path }}"
    state: "{{ item.state }}"
    recurse: "{{ item.recurse | default(omit) }}"
    owner: "{{ item.owner | default('root') }}"
    group: "{{ item.group | default('root') }}"
    mode: "{{ item.mode | default('0755') }}"
    modification_time: "{{ item.modification_time | default(omit) }}"
    access_time: "{{ item.access_time | default(omit) }}"
  loop: "{{ nginx_dirs }}"
  notify:
    - restart_nginx

- name: Install passlib with pip
  ansible.builtin.pip:
    name: "{{ nginx_pip_packages }}"

- name: Add a user to a password file and ensure permissions are set
  community.general.htpasswd:
    path: "{{ item.path }}"
    name: "{{ item.name }}"
    password: "{{ item.password }}"
    owner: "{{ item.owner }}"
    group: "{{ item.group }}"
    mode: "{{ item.mode | default('0660') }}"
  loop: "{{ nginx_auth }}"
  notify:
    - restart_nginx

- name: Copy files/templates
  ansible.builtin.template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: "{{ item.owner }}"
    group: "{{ item.group }}"
    mode: "{{ item.mode | default('0755') }}"
  loop: "{{ nginx_websites }}"
  notify:
    - restart_nginx
