nginx_packages:
  - nginx
  - python3-passlib
  # - httpd-tools

nginx_pip_packages:
  # - passlib

nginx_dirs:
  - path: /usr/share/nginx/logs
    state: directory
    owner: www-data
    group: www-data
  - path: /websites/www.example.net
    state: directory
    owner: www-data
    group: www-data
  - path: /websites/www.domain.org
    state: directory
    owner: www-data
    group: www-data
  - path: /usr/share/nginx/logs/error.log
    state: touch
    owner: www-data
    group: www-data
    mode: "0644"
    modification_time: preserve
    access_time: preserve
  - path: /etc/ssl/private
    state: directory
    mode: "0700"

nginx_templates:
  - src: nginx.conf.j2
    dest: /etc/nginx/nginx.conf
    owner: root
    group: root
    mode: "0644"
  - src: index.html.j2
    dest: /websites/www.domain.org/index.html
    site: www.domain.org
    owner: www-data
    group: www-data
    mode: "0644"
  - src: index.html.j2
    dest: /websites/www.example.net/index.html
    site: www.example.net
    owner: www-data
    group: www-data
    mode: "0644"
