---
# - name: Configure Linux host
#   hosts: all
#   become: true
#   vars:
#     setup_groups: "{{ my_groups }}"
#     setup_users: "{{ my_users }}"
#   tasks:
#     - name: Include Setup Role
#       ansible.builtin.include_role:
#         name: setup

- name: Configure nginx
  hosts: all
  become: true
  vars:
    nginx_dirs: "{{ my_dirs }}"
    nginx_websites: "{{ my_websites }}"
  tasks:
    - name: Include nginx Role
      ansible.builtin.include_role:
        name: nginx
