---
nginx_packages:
  - nginx

nginx_dirs:
  []
  # - path: # path to dir here
  #   state: directory
  #   recurse: true
  #   owner: nginx
  #   group: nginx
  #   mode: "0755"

nginx_websites:
  []
  # - src: index.html.j2
  #   dest: /websites/www.domain.org/index.html
  #   site: www.domain.org
  #   owner: nginx
  #   group: nginx
  #   mode: "0755"
