- name: Install needed packages
  when: ansible_distribution
  ansible.builtin.package:
    name: "{{ firewall_packages }}"

- name: Open services
  ansible.builtin.include_tasks: firewall.yml
  loop: "{{ firewall_services }}"
