---
- name: Upgrade all packages
  ansible.builtin.dnf:
    name: '*'
    state: latest
    update_only: true

- name: Set selinux to permissive mode
  when:
    - ansible_distribution_major_version | int > 5
  ansible.posix.selinux:
    state: permissive
    policy: targeted
    update_kernel_param: true
